services:
  frost-http:
    image: fraunhoferiosb/frost-server:latest
    environment:
      # For all settings see: https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html
      - serviceRootUrl=http://frost-http:8080/FROST-Server
      - plugins_multiDatastream.enable=false
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - persistence_idGenerationMode=ServerAndClientGenerated
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    build:
      context: ./docker
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sensorthings -U sensorthings "]
      interval: 10s
      timeout: 5s
      retries: 5

  wis2box-api:
    image: geopython/pygeoapi:latest
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
    depends_on:
      - frost-http
    environment:
      - WIS2BOX_API_BACKEND_URL=http://frost-http:8080/FROST-Server/v1.1

  wis2box-ui:
    image: internetofwater/hub2box-ui:iow
    depends_on:
      - wis2box-api
    environment:
      - WIS2BOX_URL=http://localhost:8999
      - WIS2BOX_API_URL=http://localhost:8999/api
      - serviceRootUrl=http://frost-http:8080/FROST-Server
      - WIS2BOX_API_BACKEND_URL=http://frost-http:8080/FROST-Server/v1.1

  web-proxy:
    container_name: web-proxy
    image: nginx:alpine
    restart: always
    depends_on:
      - wis2box-ui
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
    postgis_volume:
