include:
  - docker-compose-prod.yml

# The services below run in both production and locally in development
services:
  owdp-database:
    container_name: owdp-database
    build:
      context: ./docker/database
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    # apply the stat_statements in config here instead of needing to mount it in the container; postgres config path
    # varies between versions / env https://github.com/docker-library/postgres/issues/177
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

  owdp-frost:
    container_name: owdp-frost
    build:
      context: ./docker/frost
    environment:
      - serviceRootUrl=${OWDP_URL}/FROST-Server
      - persistence_db_url=jdbc:postgresql://owdp-database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 1883:1883
      - 8080:8080
    depends_on:
      - owdp-database
    restart: no

  owdp-pygeoapi:
    container_name: owdp-pygeoapi
    build:
      context: docker/pygeoapi
    depends_on:
      - owdp-frost
    restart: no
    environment:
      - API_URL=${OWDP_URL}/oapi
      - API_BACKEND_URL=http://owdp-frost:8080/FROST-Server/v1.1
      - SCRIPT_NAME=/oapi

  owdp-ui:
    image: internetofwater/hub2box-ui:owdp-limited
    container_name: owdp-ui
    depends_on:
      - owdp-pygeoapi
    environment:
      - WIS2BOX_URL=${OWDP_URL}
      - WIS2BOX_API_URL=${OWDP_URL}/oapi
      - serviceRootUrl=${OWDP_URL}/FROST-Server
