apiVersion: 1

datasources:
  - name: "grafana-postgresql-datasource"
    uid: "eeeu5ra3aww00c"
    orgId: 1
    type: "grafana-postgresql-datasource"
    typeName: "PostgreSQL"
    typeLogoUrl: "public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg"
    access: "proxy"
    url: "owdp-database:5432"
    user: "sensorthings"
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      connMaxLifetime: 14400
      database: "sensorthings"
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1400
      sslmode: "disable"
    readOnly: false

  - name: "Prometheus"
    uid: "aeeu5o1g33xmod"
    orgId: 1
    type: "prometheus"
    typeName: "Prometheus"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    access: "proxy"
    url: "http://owdp-prometheus:9090"
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: "POST"
    readOnly: false
