name: Pyright

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  uv-example:
    runs-on: ubuntu-latest
    name: python
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install pyright
        run: uv tool install pyright

      - name: Run pyright
        run: uv run pyright

