name: Validate Requirements

on:
  workflow_dispatch:
  push:
    paths:
      - "pyproject.toml"  # Trigger on changes to pyproject.toml
  pull_request:
    paths:
      - "pyproject.toml"  # Trigger on changes to pyproject.toml

jobs:
  validate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Generate new requirements.txt
        run: |
          uv export --format requirements-txt > new_requirements.txt

      - name: Compare requirements.txt
        run: |
          if ! diff -q new_requirements.txt requirements.txt; then
            echo "requirements.txt is out of sync with the project configuration:"
            diff -u requirements.txt new_requirements.txt
            exit 1
          fi
        shell: bash
